### ISSUE TITLE
Showing 52.0.1 as the latest release build which doesn't exist

### ISSUE THREAD

**Issue by kjozwiak** [luser/whatthetrain#20] opened 2017-03-10 22:09 UTC
The website is showing fx52.0.1 as being the latest version under the release channel but we just released fx52 and I don't believe a fx52.0.1 exists yet.

<img width="1172" alt="screen shot 2017-03-10 at 5 05 27 pm" src="https://cloud.githubusercontent.com/assets/2602313/23814979/c7bb1016-05b3-11e7-8055-a09e8a65112a.png">

**Comment by luser** [comment] 2017-03-11 15:21
Yeah. We don't actually have an API to get the release version, we just scrape it from https://hg.mozilla.org/releases/mozilla-release/raw-file/default/config/milestone.txt .

**Comment by kjozwiak** [comment] 2017-03-12 23:31
Gotcha, we can just close this off if that's the case unless you want to leave it opened... I wonder why the txt file is listing 52.0.1 rather than 52.0.0. Either way, I figured I would create the bug incase you weren't aware of it.

**Comment by luser** [comment] 2017-03-13 10:18
Version numbers get proactively bumped for when a dot release is planned, IIRC. I never mind having a bug filed, I wish we had an actual API to get the current release version!

**Comment by luser** [comment] 2017-03-13 10:19
Duplicate of #16

**Closed as completed by luser** 2017-03-13 10:19 UTC
Labels: duplicate
